#############################################################################
# Makefile for building: pwchat
# Generated by qmake (3.1) (Qt 5.10.0)
# Project:  pwhook.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile pwhook.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WEBSOCKETS_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -std=c++11 -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../Qt/5.10.0/Static/include -I../Qt/5.10.0/Static/include/QtWebSockets -I../Qt/5.10.0/Static/include/QtNetwork -I../Qt/5.10.0/Static/include/QtCore -I. -I../Qt/5.10.0/Static/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = pwchat1.0.0
DISTDIR = /opt/pwhook0.2.0/.tmp/pwchat1.0.0
LINK          = g++
LFLAGS        = -static-libstdc++ -static-libgcc -static -Wl,-O1
LIBS          = $(SUBLIBS) -L/opt/Qt/5.10.0/Static/plugins/bearer -lqconnmanbearer -L/opt/Qt/5.10.0/Static/lib -lqgenericbearer -lqnmbearer -lQt5DBus -lQt5WebSockets -lQt5Network -lQt5Core -lm -lz -licui18n -licuuc -licudata -lqtpcre2 -ldl -lgthread-2.0 -lglib-2.0 -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = IO/OctetsStream.cpp \
		Network/GDeliveryd.cpp \
		Protocols/WorldChat.cpp \
		Settings.cpp \
		Utils.cpp \
		Workers/BroadcasterWorker.cpp \
		echoserver.cpp \
		Server.cpp \
		main.cpp /opt/pwhook0.2.0/pwchat_plugin_import.cpp \
		moc_GDeliveryd.cpp \
		moc_Server.cpp \
		moc_BroadcasterWorker.cpp \
		moc_echoserver.cpp
OBJECTS       = OctetsStream.o \
		GDeliveryd.o \
		WorldChat.o \
		Settings.o \
		Utils.o \
		BroadcasterWorker.o \
		echoserver.o \
		Server.o \
		main.o \
		pwchat_plugin_import.o \
		moc_GDeliveryd.o \
		moc_Server.o \
		moc_BroadcasterWorker.o \
		moc_echoserver.o
DIST          = ../Qt/5.10.0/Static/mkspecs/features/spec_pre.prf \
		../Qt/5.10.0/Static/mkspecs/common/unix.conf \
		../Qt/5.10.0/Static/mkspecs/common/linux.conf \
		../Qt/5.10.0/Static/mkspecs/common/sanitize.conf \
		../Qt/5.10.0/Static/mkspecs/common/gcc-base.conf \
		../Qt/5.10.0/Static/mkspecs/common/gcc-base-unix.conf \
		../Qt/5.10.0/Static/mkspecs/common/g++-base.conf \
		../Qt/5.10.0/Static/mkspecs/common/g++-unix.conf \
		../Qt/5.10.0/Static/mkspecs/qconfig.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3danimation.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3danimation_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dcore.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dextras.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dextras_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dinput.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dlogic.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dquick.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dquickextras.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dquickinput.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dquickrender.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3drender.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3drender_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_core.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_dbus.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_gamepad.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_gamepad_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_network.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_networkauth.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_networkauth_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_purchasing.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_purchasing_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_qml.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_quick.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_remoteobjects.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_repparser.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_repparser_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_scxml.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_scxml_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_serialbus.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_serialbus_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_sql.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_waylandclient.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_webchannel.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_websockets.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_xml.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_assimpsceneimport.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_bradient.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_defaultgeometryloader.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_drm-egl-server.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_evdevgamepad.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_gltfgeometryloader.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_gltfsceneexport.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_gltfsceneimport.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_ivi-shell.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qconnmanbearer.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qmldbg_debugger.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qmldbg_local.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qmldbg_messages.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qmldbg_native.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qmldbg_profiler.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qmldbg_server.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qnmbearer.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qsqlite.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qsqlmysql.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qtpeakcanbus.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qtsocketcanbus.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qttinycanbus.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qwayland-egl.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qwayland-generic.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qwayland-xcomposite-egl.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qwayland-xcomposite-glx.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qwebgl.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_scene2d.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_shm-emulation-server.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_wayland-egl.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_xcomposite-egl.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_xcomposite-glx.pri \
		../Qt/5.10.0/Static/mkspecs/features/qt_functions.prf \
		../Qt/5.10.0/Static/mkspecs/features/qt_config.prf \
		../Qt/5.10.0/Static/mkspecs/linux-g++/qmake.conf \
		../Qt/5.10.0/Static/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../Qt/5.10.0/Static/mkspecs/features/exclusive_builds.prf \
		../Qt/5.10.0/Static/mkspecs/features/toolchain.prf \
		../Qt/5.10.0/Static/mkspecs/features/default_pre.prf \
		../Qt/5.10.0/Static/mkspecs/features/resolve_config.prf \
		../Qt/5.10.0/Static/mkspecs/features/default_post.prf \
		../Qt/5.10.0/Static/mkspecs/features/warn_on.prf \
		../Qt/5.10.0/Static/mkspecs/features/qt.prf \
		../Qt/5.10.0/Static/mkspecs/features/resources.prf \
		../Qt/5.10.0/Static/mkspecs/features/moc.prf \
		../Qt/5.10.0/Static/mkspecs/features/unix/thread.prf \
		../Qt/5.10.0/Static/mkspecs/features/qmake_use.prf \
		../Qt/5.10.0/Static/mkspecs/features/file_copies.prf \
		../Qt/5.10.0/Static/mkspecs/features/testcase_targets.prf \
		../Qt/5.10.0/Static/mkspecs/features/exceptions.prf \
		../Qt/5.10.0/Static/mkspecs/features/yacc.prf \
		../Qt/5.10.0/Static/mkspecs/features/lex.prf \
		pwhook.pro IO/Octets.h \
		IO/OctetsStream.h \
		Network/GDeliveryd.h \
		Protocols/WorldChat.h \
		Settings.h \
		Utils.h \
		Server.h \
		Workers/BroadcasterWorker.h \
		echoserver.h IO/OctetsStream.cpp \
		Network/GDeliveryd.cpp \
		Protocols/WorldChat.cpp \
		Settings.cpp \
		Utils.cpp \
		Workers/BroadcasterWorker.cpp \
		echoserver.cpp \
		Server.cpp \
		main.cpp
QMAKE_TARGET  = pwchat
DESTDIR       = 
TARGET        = pwchat


first: all
####### Build rules

$(TARGET): /opt/Qt/5.10.0/Static/lib/libQt5WebSockets.a /opt/Qt/5.10.0/Static/lib/libQt5Network.a /opt/Qt/5.10.0/Static/lib/libQt5Core.a $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: pwhook.pro ../Qt/5.10.0/Static/mkspecs/linux-g++/qmake.conf ../Qt/5.10.0/Static/mkspecs/features/spec_pre.prf \
		../Qt/5.10.0/Static/mkspecs/common/unix.conf \
		../Qt/5.10.0/Static/mkspecs/common/linux.conf \
		../Qt/5.10.0/Static/mkspecs/common/sanitize.conf \
		../Qt/5.10.0/Static/mkspecs/common/gcc-base.conf \
		../Qt/5.10.0/Static/mkspecs/common/gcc-base-unix.conf \
		../Qt/5.10.0/Static/mkspecs/common/g++-base.conf \
		../Qt/5.10.0/Static/mkspecs/common/g++-unix.conf \
		../Qt/5.10.0/Static/mkspecs/qconfig.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3danimation.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3danimation_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dcore.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dextras.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dextras_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dinput.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dlogic.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dquick.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dquickextras.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dquickinput.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dquickrender.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3drender.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3drender_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_core.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_dbus.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_gamepad.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_gamepad_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_network.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_networkauth.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_networkauth_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_purchasing.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_purchasing_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_qml.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_quick.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_remoteobjects.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_repparser.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_repparser_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_scxml.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_scxml_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_serialbus.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_serialbus_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_sql.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_waylandclient.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_webchannel.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_websockets.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_xml.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_assimpsceneimport.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_bradient.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_defaultgeometryloader.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_drm-egl-server.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_evdevgamepad.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_gltfgeometryloader.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_gltfsceneexport.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_gltfsceneimport.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_ivi-shell.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qconnmanbearer.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qmldbg_debugger.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qmldbg_local.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qmldbg_messages.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qmldbg_native.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qmldbg_profiler.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qmldbg_server.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qnmbearer.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qsqlite.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qsqlmysql.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qtpeakcanbus.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qtsocketcanbus.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qttinycanbus.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qwayland-egl.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qwayland-generic.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qwayland-xcomposite-egl.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qwayland-xcomposite-glx.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qwebgl.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_scene2d.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_shm-emulation-server.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_wayland-egl.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_xcomposite-egl.pri \
		../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_xcomposite-glx.pri \
		../Qt/5.10.0/Static/mkspecs/features/qt_functions.prf \
		../Qt/5.10.0/Static/mkspecs/features/qt_config.prf \
		../Qt/5.10.0/Static/mkspecs/linux-g++/qmake.conf \
		../Qt/5.10.0/Static/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../Qt/5.10.0/Static/mkspecs/features/exclusive_builds.prf \
		../Qt/5.10.0/Static/mkspecs/features/toolchain.prf \
		../Qt/5.10.0/Static/mkspecs/features/default_pre.prf \
		../Qt/5.10.0/Static/mkspecs/features/resolve_config.prf \
		../Qt/5.10.0/Static/mkspecs/features/default_post.prf \
		../Qt/5.10.0/Static/mkspecs/features/warn_on.prf \
		../Qt/5.10.0/Static/mkspecs/features/qt.prf \
		../Qt/5.10.0/Static/mkspecs/features/resources.prf \
		../Qt/5.10.0/Static/mkspecs/features/moc.prf \
		../Qt/5.10.0/Static/mkspecs/features/unix/thread.prf \
		../Qt/5.10.0/Static/mkspecs/features/qmake_use.prf \
		../Qt/5.10.0/Static/mkspecs/features/file_copies.prf \
		../Qt/5.10.0/Static/mkspecs/features/testcase_targets.prf \
		../Qt/5.10.0/Static/mkspecs/features/exceptions.prf \
		../Qt/5.10.0/Static/mkspecs/features/yacc.prf \
		../Qt/5.10.0/Static/mkspecs/features/lex.prf \
		pwhook.pro \
		../Qt/5.10.0/Static/plugins/bearer/libqconnmanbearer.prl \
		../Qt/5.10.0/Static/plugins/bearer/libqgenericbearer.prl \
		../Qt/5.10.0/Static/plugins/bearer/libqnmbearer.prl \
		../Qt/5.10.0/Static/lib/libQt5WebSockets.prl \
		../Qt/5.10.0/Static/lib/libQt5Network.prl \
		../Qt/5.10.0/Static/lib/libQt5Core.prl
	$(QMAKE) -o Makefile pwhook.pro
../Qt/5.10.0/Static/mkspecs/features/spec_pre.prf:
../Qt/5.10.0/Static/mkspecs/common/unix.conf:
../Qt/5.10.0/Static/mkspecs/common/linux.conf:
../Qt/5.10.0/Static/mkspecs/common/sanitize.conf:
../Qt/5.10.0/Static/mkspecs/common/gcc-base.conf:
../Qt/5.10.0/Static/mkspecs/common/gcc-base-unix.conf:
../Qt/5.10.0/Static/mkspecs/common/g++-base.conf:
../Qt/5.10.0/Static/mkspecs/common/g++-unix.conf:
../Qt/5.10.0/Static/mkspecs/qconfig.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3danimation.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3danimation_private.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dcore.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dcore_private.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dextras.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dextras_private.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dinput.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dinput_private.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dlogic.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dlogic_private.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dquick.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dquick_private.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dquickanimation.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dquickextras.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dquickinput.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dquickrender.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3drender.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_3drender_private.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_bootstrap_private.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_concurrent.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_concurrent_private.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_core.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_core_private.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_dbus.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_dbus_private.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_gamepad.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_gamepad_private.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_network.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_network_private.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_networkauth.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_networkauth_private.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_purchasing.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_purchasing_private.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_qml.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_qml_private.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_qmldebug_private.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_qmltest.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_qmltest_private.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_quick.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_quick_private.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_quickparticles_private.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_quickwidgets.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_remoteobjects.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_repparser.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_repparser_private.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_scxml.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_scxml_private.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_serialbus.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_serialbus_private.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_sql.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_sql_private.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_testlib.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_testlib_private.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_waylandclient.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_waylandclient_private.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_waylandcompositor.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_webchannel.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_webchannel_private.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_websockets.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_websockets_private.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_xml.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_lib_xml_private.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_assimpsceneimport.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_bradient.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_defaultgeometryloader.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_drm-egl-server.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_evdevgamepad.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_gltfgeometryloader.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_gltfsceneexport.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_gltfsceneimport.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_ivi-shell.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qconnmanbearer.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qgenericbearer.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qmldbg_debugger.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qmldbg_inspector.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qmldbg_local.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qmldbg_messages.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qmldbg_native.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qmldbg_profiler.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qmldbg_server.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qnmbearer.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qsqlite.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qsqlmysql.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qtpeakcanbus.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qtsocketcanbus.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qttinycanbus.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qwayland-egl.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qwayland-generic.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qwayland-xcomposite-egl.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qwayland-xcomposite-glx.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_qwebgl.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_scene2d.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_shm-emulation-server.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_wayland-egl.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_xcomposite-egl.pri:
../Qt/5.10.0/Static/mkspecs/modules/qt_plugin_xcomposite-glx.pri:
../Qt/5.10.0/Static/mkspecs/features/qt_functions.prf:
../Qt/5.10.0/Static/mkspecs/features/qt_config.prf:
../Qt/5.10.0/Static/mkspecs/linux-g++/qmake.conf:
../Qt/5.10.0/Static/mkspecs/features/spec_post.prf:
.qmake.stash:
../Qt/5.10.0/Static/mkspecs/features/exclusive_builds.prf:
../Qt/5.10.0/Static/mkspecs/features/toolchain.prf:
../Qt/5.10.0/Static/mkspecs/features/default_pre.prf:
../Qt/5.10.0/Static/mkspecs/features/resolve_config.prf:
../Qt/5.10.0/Static/mkspecs/features/default_post.prf:
../Qt/5.10.0/Static/mkspecs/features/warn_on.prf:
../Qt/5.10.0/Static/mkspecs/features/qt.prf:
../Qt/5.10.0/Static/mkspecs/features/resources.prf:
../Qt/5.10.0/Static/mkspecs/features/moc.prf:
../Qt/5.10.0/Static/mkspecs/features/unix/thread.prf:
../Qt/5.10.0/Static/mkspecs/features/qmake_use.prf:
../Qt/5.10.0/Static/mkspecs/features/file_copies.prf:
../Qt/5.10.0/Static/mkspecs/features/testcase_targets.prf:
../Qt/5.10.0/Static/mkspecs/features/exceptions.prf:
../Qt/5.10.0/Static/mkspecs/features/yacc.prf:
../Qt/5.10.0/Static/mkspecs/features/lex.prf:
pwhook.pro:
../Qt/5.10.0/Static/plugins/bearer/libqconnmanbearer.prl:
../Qt/5.10.0/Static/plugins/bearer/libqgenericbearer.prl:
../Qt/5.10.0/Static/plugins/bearer/libqnmbearer.prl:
../Qt/5.10.0/Static/lib/libQt5WebSockets.prl:
../Qt/5.10.0/Static/lib/libQt5Network.prl:
../Qt/5.10.0/Static/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile pwhook.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../Qt/5.10.0/Static/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents IO/Octets.h IO/OctetsStream.h Network/GDeliveryd.h Protocols/WorldChat.h Settings.h Utils.h Server.h Workers/BroadcasterWorker.h echoserver.h $(DISTDIR)/
	$(COPY_FILE) --parents IO/OctetsStream.cpp Network/GDeliveryd.cpp Protocols/WorldChat.cpp Settings.cpp Utils.cpp Workers/BroadcasterWorker.cpp echoserver.cpp Server.cpp main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) /opt/pwhook0.2.0/pwchat_plugin_import.cpp .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../Qt/5.10.0/Static/mkspecs/features/data/dummy.cpp
	g++ -pipe -std=c++11 -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ../Qt/5.10.0/Static/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_GDeliveryd.cpp moc_Server.cpp moc_BroadcasterWorker.cpp moc_echoserver.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_GDeliveryd.cpp moc_Server.cpp moc_BroadcasterWorker.cpp moc_echoserver.cpp
moc_GDeliveryd.cpp: ../Qt/5.10.0/Static/include/QtCore/QObject \
		../Qt/5.10.0/Static/include/QtCore/qobject.h \
		../Qt/5.10.0/Static/include/QtCore/qobjectdefs.h \
		../Qt/5.10.0/Static/include/QtCore/qnamespace.h \
		../Qt/5.10.0/Static/include/QtCore/qglobal.h \
		../Qt/5.10.0/Static/include/QtCore/qconfig-bootstrapped.h \
		../Qt/5.10.0/Static/include/QtCore/qconfig.h \
		../Qt/5.10.0/Static/include/QtCore/qtcore-config.h \
		../Qt/5.10.0/Static/include/QtCore/qsystemdetection.h \
		../Qt/5.10.0/Static/include/QtCore/qprocessordetection.h \
		../Qt/5.10.0/Static/include/QtCore/qcompilerdetection.h \
		../Qt/5.10.0/Static/include/QtCore/qtypeinfo.h \
		../Qt/5.10.0/Static/include/QtCore/qsysinfo.h \
		../Qt/5.10.0/Static/include/QtCore/qlogging.h \
		../Qt/5.10.0/Static/include/QtCore/qflags.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic.h \
		../Qt/5.10.0/Static/include/QtCore/qbasicatomic.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic_bootstrap.h \
		../Qt/5.10.0/Static/include/QtCore/qgenericatomic.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic_cxx11.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic_msvc.h \
		../Qt/5.10.0/Static/include/QtCore/qglobalstatic.h \
		../Qt/5.10.0/Static/include/QtCore/qmutex.h \
		../Qt/5.10.0/Static/include/QtCore/qnumeric.h \
		../Qt/5.10.0/Static/include/QtCore/qversiontagging.h \
		../Qt/5.10.0/Static/include/QtCore/qobjectdefs_impl.h \
		../Qt/5.10.0/Static/include/QtCore/qstring.h \
		../Qt/5.10.0/Static/include/QtCore/qchar.h \
		../Qt/5.10.0/Static/include/QtCore/qbytearray.h \
		../Qt/5.10.0/Static/include/QtCore/qrefcount.h \
		../Qt/5.10.0/Static/include/QtCore/qarraydata.h \
		../Qt/5.10.0/Static/include/QtCore/qstringliteral.h \
		../Qt/5.10.0/Static/include/QtCore/qstringalgorithms.h \
		../Qt/5.10.0/Static/include/QtCore/qstringview.h \
		../Qt/5.10.0/Static/include/QtCore/qstringbuilder.h \
		../Qt/5.10.0/Static/include/QtCore/qlist.h \
		../Qt/5.10.0/Static/include/QtCore/qalgorithms.h \
		../Qt/5.10.0/Static/include/QtCore/qiterator.h \
		../Qt/5.10.0/Static/include/QtCore/qhashfunctions.h \
		../Qt/5.10.0/Static/include/QtCore/qpair.h \
		../Qt/5.10.0/Static/include/QtCore/qbytearraylist.h \
		../Qt/5.10.0/Static/include/QtCore/qstringlist.h \
		../Qt/5.10.0/Static/include/QtCore/qregexp.h \
		../Qt/5.10.0/Static/include/QtCore/qstringmatcher.h \
		../Qt/5.10.0/Static/include/QtCore/qcoreevent.h \
		../Qt/5.10.0/Static/include/QtCore/qscopedpointer.h \
		../Qt/5.10.0/Static/include/QtCore/qmetatype.h \
		../Qt/5.10.0/Static/include/QtCore/qvarlengtharray.h \
		../Qt/5.10.0/Static/include/QtCore/qcontainerfwd.h \
		../Qt/5.10.0/Static/include/QtCore/qobject_impl.h \
		../Qt/5.10.0/Static/include/QtNetwork/QTcpSocket \
		../Qt/5.10.0/Static/include/QtNetwork/qtcpsocket.h \
		../Qt/5.10.0/Static/include/QtNetwork/qtnetworkglobal.h \
		../Qt/5.10.0/Static/include/QtNetwork/qtnetwork-config.h \
		../Qt/5.10.0/Static/include/QtNetwork/qabstractsocket.h \
		../Qt/5.10.0/Static/include/QtCore/qiodevice.h \
		../Qt/5.10.0/Static/include/QtCore/qdebug.h \
		../Qt/5.10.0/Static/include/QtCore/qhash.h \
		../Qt/5.10.0/Static/include/QtCore/qmap.h \
		../Qt/5.10.0/Static/include/QtCore/qtextstream.h \
		../Qt/5.10.0/Static/include/QtCore/qlocale.h \
		../Qt/5.10.0/Static/include/QtCore/qvariant.h \
		../Qt/5.10.0/Static/include/QtCore/qshareddata.h \
		../Qt/5.10.0/Static/include/QtCore/qvector.h \
		../Qt/5.10.0/Static/include/QtCore/qpoint.h \
		../Qt/5.10.0/Static/include/QtCore/qset.h \
		../Qt/5.10.0/Static/include/QtCore/qcontiguouscache.h \
		../Qt/5.10.0/Static/include/QtCore/qsharedpointer.h \
		../Qt/5.10.0/Static/include/QtCore/qsharedpointer_impl.h \
		Utils.h \
		../Qt/5.10.0/Static/include/QtCore/QTextCodec \
		../Qt/5.10.0/Static/include/QtCore/qtextcodec.h \
		../Qt/5.10.0/Static/include/QtCore/QDateTime \
		../Qt/5.10.0/Static/include/QtCore/qdatetime.h \
		../Qt/5.10.0/Static/include/QtCore/QString \
		IO/Octets.h \
		../Qt/5.10.0/Static/include/QtCore/QByteArray \
		Settings.h \
		../Qt/5.10.0/Static/include/QtCore/QVariant \
		../Qt/5.10.0/Static/include/QtCore/QSettings \
		../Qt/5.10.0/Static/include/QtCore/qsettings.h \
		../Qt/5.10.0/Static/include/QtCore/QMetaEnum \
		../Qt/5.10.0/Static/include/QtCore/qmetaobject.h \
		../Qt/5.10.0/Static/include/QtCore/QRegExp \
		../Qt/5.10.0/Static/include/QtCore/QList \
		Protocols/WorldChat.h \
		IO/OctetsStream.h \
		../Qt/5.10.0/Static/include/QtCore/QDataStream \
		../Qt/5.10.0/Static/include/QtCore/qdatastream.h \
		../Qt/5.10.0/Static/include/QtCore/QtEndian \
		../Qt/5.10.0/Static/include/QtCore/qendian.h \
		Network/GDeliveryd.h \
		moc_predefs.h \
		../Qt/5.10.0/Static/bin/moc
	/opt/Qt/5.10.0/Static/bin/moc $(DEFINES) --include ./moc_predefs.h -I/opt/Qt/5.10.0/Static/mkspecs/linux-g++ -I/opt/pwhook0.2.0 -I/opt/Qt/5.10.0/Static/include -I/opt/Qt/5.10.0/Static/include/QtWebSockets -I/opt/Qt/5.10.0/Static/include/QtNetwork -I/opt/Qt/5.10.0/Static/include/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Network/GDeliveryd.h -o moc_GDeliveryd.cpp

moc_Server.cpp: ../Qt/5.10.0/Static/include/QtCore/QObject \
		../Qt/5.10.0/Static/include/QtCore/qobject.h \
		../Qt/5.10.0/Static/include/QtCore/qobjectdefs.h \
		../Qt/5.10.0/Static/include/QtCore/qnamespace.h \
		../Qt/5.10.0/Static/include/QtCore/qglobal.h \
		../Qt/5.10.0/Static/include/QtCore/qconfig-bootstrapped.h \
		../Qt/5.10.0/Static/include/QtCore/qconfig.h \
		../Qt/5.10.0/Static/include/QtCore/qtcore-config.h \
		../Qt/5.10.0/Static/include/QtCore/qsystemdetection.h \
		../Qt/5.10.0/Static/include/QtCore/qprocessordetection.h \
		../Qt/5.10.0/Static/include/QtCore/qcompilerdetection.h \
		../Qt/5.10.0/Static/include/QtCore/qtypeinfo.h \
		../Qt/5.10.0/Static/include/QtCore/qsysinfo.h \
		../Qt/5.10.0/Static/include/QtCore/qlogging.h \
		../Qt/5.10.0/Static/include/QtCore/qflags.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic.h \
		../Qt/5.10.0/Static/include/QtCore/qbasicatomic.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic_bootstrap.h \
		../Qt/5.10.0/Static/include/QtCore/qgenericatomic.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic_cxx11.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic_msvc.h \
		../Qt/5.10.0/Static/include/QtCore/qglobalstatic.h \
		../Qt/5.10.0/Static/include/QtCore/qmutex.h \
		../Qt/5.10.0/Static/include/QtCore/qnumeric.h \
		../Qt/5.10.0/Static/include/QtCore/qversiontagging.h \
		../Qt/5.10.0/Static/include/QtCore/qobjectdefs_impl.h \
		../Qt/5.10.0/Static/include/QtCore/qstring.h \
		../Qt/5.10.0/Static/include/QtCore/qchar.h \
		../Qt/5.10.0/Static/include/QtCore/qbytearray.h \
		../Qt/5.10.0/Static/include/QtCore/qrefcount.h \
		../Qt/5.10.0/Static/include/QtCore/qarraydata.h \
		../Qt/5.10.0/Static/include/QtCore/qstringliteral.h \
		../Qt/5.10.0/Static/include/QtCore/qstringalgorithms.h \
		../Qt/5.10.0/Static/include/QtCore/qstringview.h \
		../Qt/5.10.0/Static/include/QtCore/qstringbuilder.h \
		../Qt/5.10.0/Static/include/QtCore/qlist.h \
		../Qt/5.10.0/Static/include/QtCore/qalgorithms.h \
		../Qt/5.10.0/Static/include/QtCore/qiterator.h \
		../Qt/5.10.0/Static/include/QtCore/qhashfunctions.h \
		../Qt/5.10.0/Static/include/QtCore/qpair.h \
		../Qt/5.10.0/Static/include/QtCore/qbytearraylist.h \
		../Qt/5.10.0/Static/include/QtCore/qstringlist.h \
		../Qt/5.10.0/Static/include/QtCore/qregexp.h \
		../Qt/5.10.0/Static/include/QtCore/qstringmatcher.h \
		../Qt/5.10.0/Static/include/QtCore/qcoreevent.h \
		../Qt/5.10.0/Static/include/QtCore/qscopedpointer.h \
		../Qt/5.10.0/Static/include/QtCore/qmetatype.h \
		../Qt/5.10.0/Static/include/QtCore/qvarlengtharray.h \
		../Qt/5.10.0/Static/include/QtCore/qcontainerfwd.h \
		../Qt/5.10.0/Static/include/QtCore/qobject_impl.h \
		../Qt/5.10.0/Static/include/QtNetwork/QTcpSocket \
		../Qt/5.10.0/Static/include/QtNetwork/qtcpsocket.h \
		../Qt/5.10.0/Static/include/QtNetwork/qtnetworkglobal.h \
		../Qt/5.10.0/Static/include/QtNetwork/qtnetwork-config.h \
		../Qt/5.10.0/Static/include/QtNetwork/qabstractsocket.h \
		../Qt/5.10.0/Static/include/QtCore/qiodevice.h \
		../Qt/5.10.0/Static/include/QtCore/qdebug.h \
		../Qt/5.10.0/Static/include/QtCore/qhash.h \
		../Qt/5.10.0/Static/include/QtCore/qmap.h \
		../Qt/5.10.0/Static/include/QtCore/qtextstream.h \
		../Qt/5.10.0/Static/include/QtCore/qlocale.h \
		../Qt/5.10.0/Static/include/QtCore/qvariant.h \
		../Qt/5.10.0/Static/include/QtCore/qshareddata.h \
		../Qt/5.10.0/Static/include/QtCore/qvector.h \
		../Qt/5.10.0/Static/include/QtCore/qpoint.h \
		../Qt/5.10.0/Static/include/QtCore/qset.h \
		../Qt/5.10.0/Static/include/QtCore/qcontiguouscache.h \
		../Qt/5.10.0/Static/include/QtCore/qsharedpointer.h \
		../Qt/5.10.0/Static/include/QtCore/qsharedpointer_impl.h \
		Server.h \
		moc_predefs.h \
		../Qt/5.10.0/Static/bin/moc
	/opt/Qt/5.10.0/Static/bin/moc $(DEFINES) --include ./moc_predefs.h -I/opt/Qt/5.10.0/Static/mkspecs/linux-g++ -I/opt/pwhook0.2.0 -I/opt/Qt/5.10.0/Static/include -I/opt/Qt/5.10.0/Static/include/QtWebSockets -I/opt/Qt/5.10.0/Static/include/QtNetwork -I/opt/Qt/5.10.0/Static/include/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Server.h -o moc_Server.cpp

moc_BroadcasterWorker.cpp: ../Qt/5.10.0/Static/include/QtCore/QObject \
		../Qt/5.10.0/Static/include/QtCore/qobject.h \
		../Qt/5.10.0/Static/include/QtCore/qobjectdefs.h \
		../Qt/5.10.0/Static/include/QtCore/qnamespace.h \
		../Qt/5.10.0/Static/include/QtCore/qglobal.h \
		../Qt/5.10.0/Static/include/QtCore/qconfig-bootstrapped.h \
		../Qt/5.10.0/Static/include/QtCore/qconfig.h \
		../Qt/5.10.0/Static/include/QtCore/qtcore-config.h \
		../Qt/5.10.0/Static/include/QtCore/qsystemdetection.h \
		../Qt/5.10.0/Static/include/QtCore/qprocessordetection.h \
		../Qt/5.10.0/Static/include/QtCore/qcompilerdetection.h \
		../Qt/5.10.0/Static/include/QtCore/qtypeinfo.h \
		../Qt/5.10.0/Static/include/QtCore/qsysinfo.h \
		../Qt/5.10.0/Static/include/QtCore/qlogging.h \
		../Qt/5.10.0/Static/include/QtCore/qflags.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic.h \
		../Qt/5.10.0/Static/include/QtCore/qbasicatomic.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic_bootstrap.h \
		../Qt/5.10.0/Static/include/QtCore/qgenericatomic.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic_cxx11.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic_msvc.h \
		../Qt/5.10.0/Static/include/QtCore/qglobalstatic.h \
		../Qt/5.10.0/Static/include/QtCore/qmutex.h \
		../Qt/5.10.0/Static/include/QtCore/qnumeric.h \
		../Qt/5.10.0/Static/include/QtCore/qversiontagging.h \
		../Qt/5.10.0/Static/include/QtCore/qobjectdefs_impl.h \
		../Qt/5.10.0/Static/include/QtCore/qstring.h \
		../Qt/5.10.0/Static/include/QtCore/qchar.h \
		../Qt/5.10.0/Static/include/QtCore/qbytearray.h \
		../Qt/5.10.0/Static/include/QtCore/qrefcount.h \
		../Qt/5.10.0/Static/include/QtCore/qarraydata.h \
		../Qt/5.10.0/Static/include/QtCore/qstringliteral.h \
		../Qt/5.10.0/Static/include/QtCore/qstringalgorithms.h \
		../Qt/5.10.0/Static/include/QtCore/qstringview.h \
		../Qt/5.10.0/Static/include/QtCore/qstringbuilder.h \
		../Qt/5.10.0/Static/include/QtCore/qlist.h \
		../Qt/5.10.0/Static/include/QtCore/qalgorithms.h \
		../Qt/5.10.0/Static/include/QtCore/qiterator.h \
		../Qt/5.10.0/Static/include/QtCore/qhashfunctions.h \
		../Qt/5.10.0/Static/include/QtCore/qpair.h \
		../Qt/5.10.0/Static/include/QtCore/qbytearraylist.h \
		../Qt/5.10.0/Static/include/QtCore/qstringlist.h \
		../Qt/5.10.0/Static/include/QtCore/qregexp.h \
		../Qt/5.10.0/Static/include/QtCore/qstringmatcher.h \
		../Qt/5.10.0/Static/include/QtCore/qcoreevent.h \
		../Qt/5.10.0/Static/include/QtCore/qscopedpointer.h \
		../Qt/5.10.0/Static/include/QtCore/qmetatype.h \
		../Qt/5.10.0/Static/include/QtCore/qvarlengtharray.h \
		../Qt/5.10.0/Static/include/QtCore/qcontainerfwd.h \
		../Qt/5.10.0/Static/include/QtCore/qobject_impl.h \
		../Qt/5.10.0/Static/include/QtCore/QFile \
		../Qt/5.10.0/Static/include/QtCore/qfile.h \
		../Qt/5.10.0/Static/include/QtCore/qfiledevice.h \
		../Qt/5.10.0/Static/include/QtCore/qiodevice.h \
		../Qt/5.10.0/Static/include/QtCore/QTimer \
		../Qt/5.10.0/Static/include/QtCore/qtimer.h \
		../Qt/5.10.0/Static/include/QtCore/qbasictimer.h \
		Settings.h \
		../Qt/5.10.0/Static/include/QtCore/QVariant \
		../Qt/5.10.0/Static/include/QtCore/qvariant.h \
		../Qt/5.10.0/Static/include/QtCore/qmap.h \
		../Qt/5.10.0/Static/include/QtCore/qdebug.h \
		../Qt/5.10.0/Static/include/QtCore/qhash.h \
		../Qt/5.10.0/Static/include/QtCore/qtextstream.h \
		../Qt/5.10.0/Static/include/QtCore/qlocale.h \
		../Qt/5.10.0/Static/include/QtCore/qshareddata.h \
		../Qt/5.10.0/Static/include/QtCore/qvector.h \
		../Qt/5.10.0/Static/include/QtCore/qpoint.h \
		../Qt/5.10.0/Static/include/QtCore/qset.h \
		../Qt/5.10.0/Static/include/QtCore/qcontiguouscache.h \
		../Qt/5.10.0/Static/include/QtCore/qsharedpointer.h \
		../Qt/5.10.0/Static/include/QtCore/qsharedpointer_impl.h \
		../Qt/5.10.0/Static/include/QtCore/QSettings \
		../Qt/5.10.0/Static/include/QtCore/qsettings.h \
		../Qt/5.10.0/Static/include/QtCore/QMetaEnum \
		../Qt/5.10.0/Static/include/QtCore/qmetaobject.h \
		../Qt/5.10.0/Static/include/QtCore/QRegExp \
		../Qt/5.10.0/Static/include/QtCore/QList \
		Utils.h \
		../Qt/5.10.0/Static/include/QtCore/QTextCodec \
		../Qt/5.10.0/Static/include/QtCore/qtextcodec.h \
		../Qt/5.10.0/Static/include/QtCore/QDateTime \
		../Qt/5.10.0/Static/include/QtCore/qdatetime.h \
		../Qt/5.10.0/Static/include/QtCore/QString \
		IO/Octets.h \
		../Qt/5.10.0/Static/include/QtCore/QByteArray \
		Network/GDeliveryd.h \
		../Qt/5.10.0/Static/include/QtNetwork/QTcpSocket \
		../Qt/5.10.0/Static/include/QtNetwork/qtcpsocket.h \
		../Qt/5.10.0/Static/include/QtNetwork/qtnetworkglobal.h \
		../Qt/5.10.0/Static/include/QtNetwork/qtnetwork-config.h \
		../Qt/5.10.0/Static/include/QtNetwork/qabstractsocket.h \
		Protocols/WorldChat.h \
		IO/OctetsStream.h \
		../Qt/5.10.0/Static/include/QtCore/QDataStream \
		../Qt/5.10.0/Static/include/QtCore/qdatastream.h \
		../Qt/5.10.0/Static/include/QtCore/QtEndian \
		../Qt/5.10.0/Static/include/QtCore/qendian.h \
		Workers/BroadcasterWorker.h \
		moc_predefs.h \
		../Qt/5.10.0/Static/bin/moc
	/opt/Qt/5.10.0/Static/bin/moc $(DEFINES) --include ./moc_predefs.h -I/opt/Qt/5.10.0/Static/mkspecs/linux-g++ -I/opt/pwhook0.2.0 -I/opt/Qt/5.10.0/Static/include -I/opt/Qt/5.10.0/Static/include/QtWebSockets -I/opt/Qt/5.10.0/Static/include/QtNetwork -I/opt/Qt/5.10.0/Static/include/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Workers/BroadcasterWorker.h -o moc_BroadcasterWorker.cpp

moc_echoserver.cpp: ../Qt/5.10.0/Static/include/QtCore/QObject \
		../Qt/5.10.0/Static/include/QtCore/qobject.h \
		../Qt/5.10.0/Static/include/QtCore/qobjectdefs.h \
		../Qt/5.10.0/Static/include/QtCore/qnamespace.h \
		../Qt/5.10.0/Static/include/QtCore/qglobal.h \
		../Qt/5.10.0/Static/include/QtCore/qconfig-bootstrapped.h \
		../Qt/5.10.0/Static/include/QtCore/qconfig.h \
		../Qt/5.10.0/Static/include/QtCore/qtcore-config.h \
		../Qt/5.10.0/Static/include/QtCore/qsystemdetection.h \
		../Qt/5.10.0/Static/include/QtCore/qprocessordetection.h \
		../Qt/5.10.0/Static/include/QtCore/qcompilerdetection.h \
		../Qt/5.10.0/Static/include/QtCore/qtypeinfo.h \
		../Qt/5.10.0/Static/include/QtCore/qsysinfo.h \
		../Qt/5.10.0/Static/include/QtCore/qlogging.h \
		../Qt/5.10.0/Static/include/QtCore/qflags.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic.h \
		../Qt/5.10.0/Static/include/QtCore/qbasicatomic.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic_bootstrap.h \
		../Qt/5.10.0/Static/include/QtCore/qgenericatomic.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic_cxx11.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic_msvc.h \
		../Qt/5.10.0/Static/include/QtCore/qglobalstatic.h \
		../Qt/5.10.0/Static/include/QtCore/qmutex.h \
		../Qt/5.10.0/Static/include/QtCore/qnumeric.h \
		../Qt/5.10.0/Static/include/QtCore/qversiontagging.h \
		../Qt/5.10.0/Static/include/QtCore/qobjectdefs_impl.h \
		../Qt/5.10.0/Static/include/QtCore/qstring.h \
		../Qt/5.10.0/Static/include/QtCore/qchar.h \
		../Qt/5.10.0/Static/include/QtCore/qbytearray.h \
		../Qt/5.10.0/Static/include/QtCore/qrefcount.h \
		../Qt/5.10.0/Static/include/QtCore/qarraydata.h \
		../Qt/5.10.0/Static/include/QtCore/qstringliteral.h \
		../Qt/5.10.0/Static/include/QtCore/qstringalgorithms.h \
		../Qt/5.10.0/Static/include/QtCore/qstringview.h \
		../Qt/5.10.0/Static/include/QtCore/qstringbuilder.h \
		../Qt/5.10.0/Static/include/QtCore/qlist.h \
		../Qt/5.10.0/Static/include/QtCore/qalgorithms.h \
		../Qt/5.10.0/Static/include/QtCore/qiterator.h \
		../Qt/5.10.0/Static/include/QtCore/qhashfunctions.h \
		../Qt/5.10.0/Static/include/QtCore/qpair.h \
		../Qt/5.10.0/Static/include/QtCore/qbytearraylist.h \
		../Qt/5.10.0/Static/include/QtCore/qstringlist.h \
		../Qt/5.10.0/Static/include/QtCore/qregexp.h \
		../Qt/5.10.0/Static/include/QtCore/qstringmatcher.h \
		../Qt/5.10.0/Static/include/QtCore/qcoreevent.h \
		../Qt/5.10.0/Static/include/QtCore/qscopedpointer.h \
		../Qt/5.10.0/Static/include/QtCore/qmetatype.h \
		../Qt/5.10.0/Static/include/QtCore/qvarlengtharray.h \
		../Qt/5.10.0/Static/include/QtCore/qcontainerfwd.h \
		../Qt/5.10.0/Static/include/QtCore/qobject_impl.h \
		../Qt/5.10.0/Static/include/QtCore/QList \
		../Qt/5.10.0/Static/include/QtCore/QByteArray \
		../Qt/5.10.0/Static/include/QtNetwork/QTcpSocket \
		../Qt/5.10.0/Static/include/QtNetwork/qtcpsocket.h \
		../Qt/5.10.0/Static/include/QtNetwork/qtnetworkglobal.h \
		../Qt/5.10.0/Static/include/QtNetwork/qtnetwork-config.h \
		../Qt/5.10.0/Static/include/QtNetwork/qabstractsocket.h \
		../Qt/5.10.0/Static/include/QtCore/qiodevice.h \
		../Qt/5.10.0/Static/include/QtCore/qdebug.h \
		../Qt/5.10.0/Static/include/QtCore/qhash.h \
		../Qt/5.10.0/Static/include/QtCore/qmap.h \
		../Qt/5.10.0/Static/include/QtCore/qtextstream.h \
		../Qt/5.10.0/Static/include/QtCore/qlocale.h \
		../Qt/5.10.0/Static/include/QtCore/qvariant.h \
		../Qt/5.10.0/Static/include/QtCore/qshareddata.h \
		../Qt/5.10.0/Static/include/QtCore/qvector.h \
		../Qt/5.10.0/Static/include/QtCore/qpoint.h \
		../Qt/5.10.0/Static/include/QtCore/qset.h \
		../Qt/5.10.0/Static/include/QtCore/qcontiguouscache.h \
		../Qt/5.10.0/Static/include/QtCore/qsharedpointer.h \
		../Qt/5.10.0/Static/include/QtCore/qsharedpointer_impl.h \
		echoserver.h \
		moc_predefs.h \
		../Qt/5.10.0/Static/bin/moc
	/opt/Qt/5.10.0/Static/bin/moc $(DEFINES) --include ./moc_predefs.h -I/opt/Qt/5.10.0/Static/mkspecs/linux-g++ -I/opt/pwhook0.2.0 -I/opt/Qt/5.10.0/Static/include -I/opt/Qt/5.10.0/Static/include/QtWebSockets -I/opt/Qt/5.10.0/Static/include/QtNetwork -I/opt/Qt/5.10.0/Static/include/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include echoserver.h -o moc_echoserver.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

OctetsStream.o: IO/OctetsStream.cpp IO/OctetsStream.h \
		../Qt/5.10.0/Static/include/QtCore/QObject \
		../Qt/5.10.0/Static/include/QtCore/qobject.h \
		../Qt/5.10.0/Static/include/QtCore/qobjectdefs.h \
		../Qt/5.10.0/Static/include/QtCore/qnamespace.h \
		../Qt/5.10.0/Static/include/QtCore/qglobal.h \
		../Qt/5.10.0/Static/include/QtCore/qconfig-bootstrapped.h \
		../Qt/5.10.0/Static/include/QtCore/qconfig.h \
		../Qt/5.10.0/Static/include/QtCore/qtcore-config.h \
		../Qt/5.10.0/Static/include/QtCore/qsystemdetection.h \
		../Qt/5.10.0/Static/include/QtCore/qprocessordetection.h \
		../Qt/5.10.0/Static/include/QtCore/qcompilerdetection.h \
		../Qt/5.10.0/Static/include/QtCore/qtypeinfo.h \
		../Qt/5.10.0/Static/include/QtCore/qsysinfo.h \
		../Qt/5.10.0/Static/include/QtCore/qlogging.h \
		../Qt/5.10.0/Static/include/QtCore/qflags.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic.h \
		../Qt/5.10.0/Static/include/QtCore/qbasicatomic.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic_bootstrap.h \
		../Qt/5.10.0/Static/include/QtCore/qgenericatomic.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic_cxx11.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic_msvc.h \
		../Qt/5.10.0/Static/include/QtCore/qglobalstatic.h \
		../Qt/5.10.0/Static/include/QtCore/qmutex.h \
		../Qt/5.10.0/Static/include/QtCore/qnumeric.h \
		../Qt/5.10.0/Static/include/QtCore/qversiontagging.h \
		../Qt/5.10.0/Static/include/QtCore/qobjectdefs_impl.h \
		../Qt/5.10.0/Static/include/QtCore/qstring.h \
		../Qt/5.10.0/Static/include/QtCore/qchar.h \
		../Qt/5.10.0/Static/include/QtCore/qbytearray.h \
		../Qt/5.10.0/Static/include/QtCore/qrefcount.h \
		../Qt/5.10.0/Static/include/QtCore/qarraydata.h \
		../Qt/5.10.0/Static/include/QtCore/qstringliteral.h \
		../Qt/5.10.0/Static/include/QtCore/qstringalgorithms.h \
		../Qt/5.10.0/Static/include/QtCore/qstringview.h \
		../Qt/5.10.0/Static/include/QtCore/qstringbuilder.h \
		../Qt/5.10.0/Static/include/QtCore/qlist.h \
		../Qt/5.10.0/Static/include/QtCore/qalgorithms.h \
		../Qt/5.10.0/Static/include/QtCore/qiterator.h \
		../Qt/5.10.0/Static/include/QtCore/qhashfunctions.h \
		../Qt/5.10.0/Static/include/QtCore/qpair.h \
		../Qt/5.10.0/Static/include/QtCore/qbytearraylist.h \
		../Qt/5.10.0/Static/include/QtCore/qstringlist.h \
		../Qt/5.10.0/Static/include/QtCore/qregexp.h \
		../Qt/5.10.0/Static/include/QtCore/qstringmatcher.h \
		../Qt/5.10.0/Static/include/QtCore/qcoreevent.h \
		../Qt/5.10.0/Static/include/QtCore/qscopedpointer.h \
		../Qt/5.10.0/Static/include/QtCore/qmetatype.h \
		../Qt/5.10.0/Static/include/QtCore/qvarlengtharray.h \
		../Qt/5.10.0/Static/include/QtCore/qcontainerfwd.h \
		../Qt/5.10.0/Static/include/QtCore/qobject_impl.h \
		../Qt/5.10.0/Static/include/QtCore/QByteArray \
		../Qt/5.10.0/Static/include/QtCore/QDataStream \
		../Qt/5.10.0/Static/include/QtCore/qdatastream.h \
		../Qt/5.10.0/Static/include/QtCore/qiodevice.h \
		../Qt/5.10.0/Static/include/QtCore/QtEndian \
		../Qt/5.10.0/Static/include/QtCore/qendian.h \
		../Qt/5.10.0/Static/include/QtNetwork/QTcpSocket \
		../Qt/5.10.0/Static/include/QtNetwork/qtcpsocket.h \
		../Qt/5.10.0/Static/include/QtNetwork/qtnetworkglobal.h \
		../Qt/5.10.0/Static/include/QtNetwork/qtnetwork-config.h \
		../Qt/5.10.0/Static/include/QtNetwork/qabstractsocket.h \
		../Qt/5.10.0/Static/include/QtCore/qdebug.h \
		../Qt/5.10.0/Static/include/QtCore/qhash.h \
		../Qt/5.10.0/Static/include/QtCore/qmap.h \
		../Qt/5.10.0/Static/include/QtCore/qtextstream.h \
		../Qt/5.10.0/Static/include/QtCore/qlocale.h \
		../Qt/5.10.0/Static/include/QtCore/qvariant.h \
		../Qt/5.10.0/Static/include/QtCore/qshareddata.h \
		../Qt/5.10.0/Static/include/QtCore/qvector.h \
		../Qt/5.10.0/Static/include/QtCore/qpoint.h \
		../Qt/5.10.0/Static/include/QtCore/qset.h \
		../Qt/5.10.0/Static/include/QtCore/qcontiguouscache.h \
		../Qt/5.10.0/Static/include/QtCore/qsharedpointer.h \
		../Qt/5.10.0/Static/include/QtCore/qsharedpointer_impl.h \
		IO/Octets.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OctetsStream.o IO/OctetsStream.cpp

GDeliveryd.o: Network/GDeliveryd.cpp Network/GDeliveryd.h \
		../Qt/5.10.0/Static/include/QtCore/QObject \
		../Qt/5.10.0/Static/include/QtCore/qobject.h \
		../Qt/5.10.0/Static/include/QtCore/qobjectdefs.h \
		../Qt/5.10.0/Static/include/QtCore/qnamespace.h \
		../Qt/5.10.0/Static/include/QtCore/qglobal.h \
		../Qt/5.10.0/Static/include/QtCore/qconfig-bootstrapped.h \
		../Qt/5.10.0/Static/include/QtCore/qconfig.h \
		../Qt/5.10.0/Static/include/QtCore/qtcore-config.h \
		../Qt/5.10.0/Static/include/QtCore/qsystemdetection.h \
		../Qt/5.10.0/Static/include/QtCore/qprocessordetection.h \
		../Qt/5.10.0/Static/include/QtCore/qcompilerdetection.h \
		../Qt/5.10.0/Static/include/QtCore/qtypeinfo.h \
		../Qt/5.10.0/Static/include/QtCore/qsysinfo.h \
		../Qt/5.10.0/Static/include/QtCore/qlogging.h \
		../Qt/5.10.0/Static/include/QtCore/qflags.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic.h \
		../Qt/5.10.0/Static/include/QtCore/qbasicatomic.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic_bootstrap.h \
		../Qt/5.10.0/Static/include/QtCore/qgenericatomic.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic_cxx11.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic_msvc.h \
		../Qt/5.10.0/Static/include/QtCore/qglobalstatic.h \
		../Qt/5.10.0/Static/include/QtCore/qmutex.h \
		../Qt/5.10.0/Static/include/QtCore/qnumeric.h \
		../Qt/5.10.0/Static/include/QtCore/qversiontagging.h \
		../Qt/5.10.0/Static/include/QtCore/qobjectdefs_impl.h \
		../Qt/5.10.0/Static/include/QtCore/qstring.h \
		../Qt/5.10.0/Static/include/QtCore/qchar.h \
		../Qt/5.10.0/Static/include/QtCore/qbytearray.h \
		../Qt/5.10.0/Static/include/QtCore/qrefcount.h \
		../Qt/5.10.0/Static/include/QtCore/qarraydata.h \
		../Qt/5.10.0/Static/include/QtCore/qstringliteral.h \
		../Qt/5.10.0/Static/include/QtCore/qstringalgorithms.h \
		../Qt/5.10.0/Static/include/QtCore/qstringview.h \
		../Qt/5.10.0/Static/include/QtCore/qstringbuilder.h \
		../Qt/5.10.0/Static/include/QtCore/qlist.h \
		../Qt/5.10.0/Static/include/QtCore/qalgorithms.h \
		../Qt/5.10.0/Static/include/QtCore/qiterator.h \
		../Qt/5.10.0/Static/include/QtCore/qhashfunctions.h \
		../Qt/5.10.0/Static/include/QtCore/qpair.h \
		../Qt/5.10.0/Static/include/QtCore/qbytearraylist.h \
		../Qt/5.10.0/Static/include/QtCore/qstringlist.h \
		../Qt/5.10.0/Static/include/QtCore/qregexp.h \
		../Qt/5.10.0/Static/include/QtCore/qstringmatcher.h \
		../Qt/5.10.0/Static/include/QtCore/qcoreevent.h \
		../Qt/5.10.0/Static/include/QtCore/qscopedpointer.h \
		../Qt/5.10.0/Static/include/QtCore/qmetatype.h \
		../Qt/5.10.0/Static/include/QtCore/qvarlengtharray.h \
		../Qt/5.10.0/Static/include/QtCore/qcontainerfwd.h \
		../Qt/5.10.0/Static/include/QtCore/qobject_impl.h \
		../Qt/5.10.0/Static/include/QtNetwork/QTcpSocket \
		../Qt/5.10.0/Static/include/QtNetwork/qtcpsocket.h \
		../Qt/5.10.0/Static/include/QtNetwork/qtnetworkglobal.h \
		../Qt/5.10.0/Static/include/QtNetwork/qtnetwork-config.h \
		../Qt/5.10.0/Static/include/QtNetwork/qabstractsocket.h \
		../Qt/5.10.0/Static/include/QtCore/qiodevice.h \
		../Qt/5.10.0/Static/include/QtCore/qdebug.h \
		../Qt/5.10.0/Static/include/QtCore/qhash.h \
		../Qt/5.10.0/Static/include/QtCore/qmap.h \
		../Qt/5.10.0/Static/include/QtCore/qtextstream.h \
		../Qt/5.10.0/Static/include/QtCore/qlocale.h \
		../Qt/5.10.0/Static/include/QtCore/qvariant.h \
		../Qt/5.10.0/Static/include/QtCore/qshareddata.h \
		../Qt/5.10.0/Static/include/QtCore/qvector.h \
		../Qt/5.10.0/Static/include/QtCore/qpoint.h \
		../Qt/5.10.0/Static/include/QtCore/qset.h \
		../Qt/5.10.0/Static/include/QtCore/qcontiguouscache.h \
		../Qt/5.10.0/Static/include/QtCore/qsharedpointer.h \
		../Qt/5.10.0/Static/include/QtCore/qsharedpointer_impl.h \
		Utils.h \
		../Qt/5.10.0/Static/include/QtCore/QTextCodec \
		../Qt/5.10.0/Static/include/QtCore/qtextcodec.h \
		../Qt/5.10.0/Static/include/QtCore/QDateTime \
		../Qt/5.10.0/Static/include/QtCore/qdatetime.h \
		../Qt/5.10.0/Static/include/QtCore/QString \
		IO/Octets.h \
		../Qt/5.10.0/Static/include/QtCore/QByteArray \
		Settings.h \
		../Qt/5.10.0/Static/include/QtCore/QVariant \
		../Qt/5.10.0/Static/include/QtCore/QSettings \
		../Qt/5.10.0/Static/include/QtCore/qsettings.h \
		../Qt/5.10.0/Static/include/QtCore/QMetaEnum \
		../Qt/5.10.0/Static/include/QtCore/qmetaobject.h \
		../Qt/5.10.0/Static/include/QtCore/QRegExp \
		../Qt/5.10.0/Static/include/QtCore/QList \
		Protocols/WorldChat.h \
		IO/OctetsStream.h \
		../Qt/5.10.0/Static/include/QtCore/QDataStream \
		../Qt/5.10.0/Static/include/QtCore/qdatastream.h \
		../Qt/5.10.0/Static/include/QtCore/QtEndian \
		../Qt/5.10.0/Static/include/QtCore/qendian.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GDeliveryd.o Network/GDeliveryd.cpp

WorldChat.o: Protocols/WorldChat.cpp Protocols/WorldChat.h \
		../Qt/5.10.0/Static/include/QtCore/QObject \
		../Qt/5.10.0/Static/include/QtCore/qobject.h \
		../Qt/5.10.0/Static/include/QtCore/qobjectdefs.h \
		../Qt/5.10.0/Static/include/QtCore/qnamespace.h \
		../Qt/5.10.0/Static/include/QtCore/qglobal.h \
		../Qt/5.10.0/Static/include/QtCore/qconfig-bootstrapped.h \
		../Qt/5.10.0/Static/include/QtCore/qconfig.h \
		../Qt/5.10.0/Static/include/QtCore/qtcore-config.h \
		../Qt/5.10.0/Static/include/QtCore/qsystemdetection.h \
		../Qt/5.10.0/Static/include/QtCore/qprocessordetection.h \
		../Qt/5.10.0/Static/include/QtCore/qcompilerdetection.h \
		../Qt/5.10.0/Static/include/QtCore/qtypeinfo.h \
		../Qt/5.10.0/Static/include/QtCore/qsysinfo.h \
		../Qt/5.10.0/Static/include/QtCore/qlogging.h \
		../Qt/5.10.0/Static/include/QtCore/qflags.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic.h \
		../Qt/5.10.0/Static/include/QtCore/qbasicatomic.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic_bootstrap.h \
		../Qt/5.10.0/Static/include/QtCore/qgenericatomic.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic_cxx11.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic_msvc.h \
		../Qt/5.10.0/Static/include/QtCore/qglobalstatic.h \
		../Qt/5.10.0/Static/include/QtCore/qmutex.h \
		../Qt/5.10.0/Static/include/QtCore/qnumeric.h \
		../Qt/5.10.0/Static/include/QtCore/qversiontagging.h \
		../Qt/5.10.0/Static/include/QtCore/qobjectdefs_impl.h \
		../Qt/5.10.0/Static/include/QtCore/qstring.h \
		../Qt/5.10.0/Static/include/QtCore/qchar.h \
		../Qt/5.10.0/Static/include/QtCore/qbytearray.h \
		../Qt/5.10.0/Static/include/QtCore/qrefcount.h \
		../Qt/5.10.0/Static/include/QtCore/qarraydata.h \
		../Qt/5.10.0/Static/include/QtCore/qstringliteral.h \
		../Qt/5.10.0/Static/include/QtCore/qstringalgorithms.h \
		../Qt/5.10.0/Static/include/QtCore/qstringview.h \
		../Qt/5.10.0/Static/include/QtCore/qstringbuilder.h \
		../Qt/5.10.0/Static/include/QtCore/qlist.h \
		../Qt/5.10.0/Static/include/QtCore/qalgorithms.h \
		../Qt/5.10.0/Static/include/QtCore/qiterator.h \
		../Qt/5.10.0/Static/include/QtCore/qhashfunctions.h \
		../Qt/5.10.0/Static/include/QtCore/qpair.h \
		../Qt/5.10.0/Static/include/QtCore/qbytearraylist.h \
		../Qt/5.10.0/Static/include/QtCore/qstringlist.h \
		../Qt/5.10.0/Static/include/QtCore/qregexp.h \
		../Qt/5.10.0/Static/include/QtCore/qstringmatcher.h \
		../Qt/5.10.0/Static/include/QtCore/qcoreevent.h \
		../Qt/5.10.0/Static/include/QtCore/qscopedpointer.h \
		../Qt/5.10.0/Static/include/QtCore/qmetatype.h \
		../Qt/5.10.0/Static/include/QtCore/qvarlengtharray.h \
		../Qt/5.10.0/Static/include/QtCore/qcontainerfwd.h \
		../Qt/5.10.0/Static/include/QtCore/qobject_impl.h \
		IO/OctetsStream.h \
		../Qt/5.10.0/Static/include/QtCore/QByteArray \
		../Qt/5.10.0/Static/include/QtCore/QDataStream \
		../Qt/5.10.0/Static/include/QtCore/qdatastream.h \
		../Qt/5.10.0/Static/include/QtCore/qiodevice.h \
		../Qt/5.10.0/Static/include/QtCore/QtEndian \
		../Qt/5.10.0/Static/include/QtCore/qendian.h \
		../Qt/5.10.0/Static/include/QtNetwork/QTcpSocket \
		../Qt/5.10.0/Static/include/QtNetwork/qtcpsocket.h \
		../Qt/5.10.0/Static/include/QtNetwork/qtnetworkglobal.h \
		../Qt/5.10.0/Static/include/QtNetwork/qtnetwork-config.h \
		../Qt/5.10.0/Static/include/QtNetwork/qabstractsocket.h \
		../Qt/5.10.0/Static/include/QtCore/qdebug.h \
		../Qt/5.10.0/Static/include/QtCore/qhash.h \
		../Qt/5.10.0/Static/include/QtCore/qmap.h \
		../Qt/5.10.0/Static/include/QtCore/qtextstream.h \
		../Qt/5.10.0/Static/include/QtCore/qlocale.h \
		../Qt/5.10.0/Static/include/QtCore/qvariant.h \
		../Qt/5.10.0/Static/include/QtCore/qshareddata.h \
		../Qt/5.10.0/Static/include/QtCore/qvector.h \
		../Qt/5.10.0/Static/include/QtCore/qpoint.h \
		../Qt/5.10.0/Static/include/QtCore/qset.h \
		../Qt/5.10.0/Static/include/QtCore/qcontiguouscache.h \
		../Qt/5.10.0/Static/include/QtCore/qsharedpointer.h \
		../Qt/5.10.0/Static/include/QtCore/qsharedpointer_impl.h \
		IO/Octets.h \
		Utils.h \
		../Qt/5.10.0/Static/include/QtCore/QTextCodec \
		../Qt/5.10.0/Static/include/QtCore/qtextcodec.h \
		../Qt/5.10.0/Static/include/QtCore/QDateTime \
		../Qt/5.10.0/Static/include/QtCore/qdatetime.h \
		../Qt/5.10.0/Static/include/QtCore/QString
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WorldChat.o Protocols/WorldChat.cpp

Settings.o: Settings.cpp Settings.h \
		../Qt/5.10.0/Static/include/QtCore/QVariant \
		../Qt/5.10.0/Static/include/QtCore/qvariant.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic.h \
		../Qt/5.10.0/Static/include/QtCore/qglobal.h \
		../Qt/5.10.0/Static/include/QtCore/qconfig-bootstrapped.h \
		../Qt/5.10.0/Static/include/QtCore/qconfig.h \
		../Qt/5.10.0/Static/include/QtCore/qtcore-config.h \
		../Qt/5.10.0/Static/include/QtCore/qsystemdetection.h \
		../Qt/5.10.0/Static/include/QtCore/qprocessordetection.h \
		../Qt/5.10.0/Static/include/QtCore/qcompilerdetection.h \
		../Qt/5.10.0/Static/include/QtCore/qtypeinfo.h \
		../Qt/5.10.0/Static/include/QtCore/qsysinfo.h \
		../Qt/5.10.0/Static/include/QtCore/qlogging.h \
		../Qt/5.10.0/Static/include/QtCore/qflags.h \
		../Qt/5.10.0/Static/include/QtCore/qglobalstatic.h \
		../Qt/5.10.0/Static/include/QtCore/qmutex.h \
		../Qt/5.10.0/Static/include/QtCore/qnumeric.h \
		../Qt/5.10.0/Static/include/QtCore/qversiontagging.h \
		../Qt/5.10.0/Static/include/QtCore/qbasicatomic.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic_bootstrap.h \
		../Qt/5.10.0/Static/include/QtCore/qgenericatomic.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic_cxx11.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic_msvc.h \
		../Qt/5.10.0/Static/include/QtCore/qbytearray.h \
		../Qt/5.10.0/Static/include/QtCore/qrefcount.h \
		../Qt/5.10.0/Static/include/QtCore/qnamespace.h \
		../Qt/5.10.0/Static/include/QtCore/qarraydata.h \
		../Qt/5.10.0/Static/include/QtCore/qlist.h \
		../Qt/5.10.0/Static/include/QtCore/qalgorithms.h \
		../Qt/5.10.0/Static/include/QtCore/qiterator.h \
		../Qt/5.10.0/Static/include/QtCore/qhashfunctions.h \
		../Qt/5.10.0/Static/include/QtCore/qstring.h \
		../Qt/5.10.0/Static/include/QtCore/qchar.h \
		../Qt/5.10.0/Static/include/QtCore/qstringliteral.h \
		../Qt/5.10.0/Static/include/QtCore/qstringalgorithms.h \
		../Qt/5.10.0/Static/include/QtCore/qstringview.h \
		../Qt/5.10.0/Static/include/QtCore/qstringbuilder.h \
		../Qt/5.10.0/Static/include/QtCore/qpair.h \
		../Qt/5.10.0/Static/include/QtCore/qbytearraylist.h \
		../Qt/5.10.0/Static/include/QtCore/qstringlist.h \
		../Qt/5.10.0/Static/include/QtCore/qregexp.h \
		../Qt/5.10.0/Static/include/QtCore/qstringmatcher.h \
		../Qt/5.10.0/Static/include/QtCore/qmetatype.h \
		../Qt/5.10.0/Static/include/QtCore/qvarlengtharray.h \
		../Qt/5.10.0/Static/include/QtCore/qcontainerfwd.h \
		../Qt/5.10.0/Static/include/QtCore/qobjectdefs.h \
		../Qt/5.10.0/Static/include/QtCore/qobjectdefs_impl.h \
		../Qt/5.10.0/Static/include/QtCore/qmap.h \
		../Qt/5.10.0/Static/include/QtCore/qdebug.h \
		../Qt/5.10.0/Static/include/QtCore/qhash.h \
		../Qt/5.10.0/Static/include/QtCore/qtextstream.h \
		../Qt/5.10.0/Static/include/QtCore/qiodevice.h \
		../Qt/5.10.0/Static/include/QtCore/qobject.h \
		../Qt/5.10.0/Static/include/QtCore/qcoreevent.h \
		../Qt/5.10.0/Static/include/QtCore/qscopedpointer.h \
		../Qt/5.10.0/Static/include/QtCore/qobject_impl.h \
		../Qt/5.10.0/Static/include/QtCore/qlocale.h \
		../Qt/5.10.0/Static/include/QtCore/qshareddata.h \
		../Qt/5.10.0/Static/include/QtCore/qvector.h \
		../Qt/5.10.0/Static/include/QtCore/qpoint.h \
		../Qt/5.10.0/Static/include/QtCore/qset.h \
		../Qt/5.10.0/Static/include/QtCore/qcontiguouscache.h \
		../Qt/5.10.0/Static/include/QtCore/qsharedpointer.h \
		../Qt/5.10.0/Static/include/QtCore/qsharedpointer_impl.h \
		../Qt/5.10.0/Static/include/QtCore/QSettings \
		../Qt/5.10.0/Static/include/QtCore/qsettings.h \
		../Qt/5.10.0/Static/include/QtCore/QMetaEnum \
		../Qt/5.10.0/Static/include/QtCore/qmetaobject.h \
		../Qt/5.10.0/Static/include/QtCore/QRegExp \
		../Qt/5.10.0/Static/include/QtCore/QList \
		Utils.h \
		../Qt/5.10.0/Static/include/QtCore/QTextCodec \
		../Qt/5.10.0/Static/include/QtCore/qtextcodec.h \
		../Qt/5.10.0/Static/include/QtCore/QDateTime \
		../Qt/5.10.0/Static/include/QtCore/qdatetime.h \
		../Qt/5.10.0/Static/include/QtCore/QString \
		IO/Octets.h \
		../Qt/5.10.0/Static/include/QtCore/QByteArray
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Settings.o Settings.cpp

Utils.o: Utils.cpp Utils.h \
		../Qt/5.10.0/Static/include/QtCore/QTextCodec \
		../Qt/5.10.0/Static/include/QtCore/qtextcodec.h \
		../Qt/5.10.0/Static/include/QtCore/qstring.h \
		../Qt/5.10.0/Static/include/QtCore/qchar.h \
		../Qt/5.10.0/Static/include/QtCore/qglobal.h \
		../Qt/5.10.0/Static/include/QtCore/qconfig-bootstrapped.h \
		../Qt/5.10.0/Static/include/QtCore/qconfig.h \
		../Qt/5.10.0/Static/include/QtCore/qtcore-config.h \
		../Qt/5.10.0/Static/include/QtCore/qsystemdetection.h \
		../Qt/5.10.0/Static/include/QtCore/qprocessordetection.h \
		../Qt/5.10.0/Static/include/QtCore/qcompilerdetection.h \
		../Qt/5.10.0/Static/include/QtCore/qtypeinfo.h \
		../Qt/5.10.0/Static/include/QtCore/qsysinfo.h \
		../Qt/5.10.0/Static/include/QtCore/qlogging.h \
		../Qt/5.10.0/Static/include/QtCore/qflags.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic.h \
		../Qt/5.10.0/Static/include/QtCore/qbasicatomic.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic_bootstrap.h \
		../Qt/5.10.0/Static/include/QtCore/qgenericatomic.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic_cxx11.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic_msvc.h \
		../Qt/5.10.0/Static/include/QtCore/qglobalstatic.h \
		../Qt/5.10.0/Static/include/QtCore/qmutex.h \
		../Qt/5.10.0/Static/include/QtCore/qnumeric.h \
		../Qt/5.10.0/Static/include/QtCore/qversiontagging.h \
		../Qt/5.10.0/Static/include/QtCore/qbytearray.h \
		../Qt/5.10.0/Static/include/QtCore/qrefcount.h \
		../Qt/5.10.0/Static/include/QtCore/qnamespace.h \
		../Qt/5.10.0/Static/include/QtCore/qarraydata.h \
		../Qt/5.10.0/Static/include/QtCore/qstringliteral.h \
		../Qt/5.10.0/Static/include/QtCore/qstringalgorithms.h \
		../Qt/5.10.0/Static/include/QtCore/qstringview.h \
		../Qt/5.10.0/Static/include/QtCore/qstringbuilder.h \
		../Qt/5.10.0/Static/include/QtCore/qlist.h \
		../Qt/5.10.0/Static/include/QtCore/qalgorithms.h \
		../Qt/5.10.0/Static/include/QtCore/qiterator.h \
		../Qt/5.10.0/Static/include/QtCore/qhashfunctions.h \
		../Qt/5.10.0/Static/include/QtCore/qpair.h \
		../Qt/5.10.0/Static/include/QtCore/qbytearraylist.h \
		../Qt/5.10.0/Static/include/QtCore/qstringlist.h \
		../Qt/5.10.0/Static/include/QtCore/qregexp.h \
		../Qt/5.10.0/Static/include/QtCore/qstringmatcher.h \
		../Qt/5.10.0/Static/include/QtCore/QDateTime \
		../Qt/5.10.0/Static/include/QtCore/qdatetime.h \
		../Qt/5.10.0/Static/include/QtCore/qshareddata.h \
		../Qt/5.10.0/Static/include/QtCore/qhash.h \
		../Qt/5.10.0/Static/include/QtCore/QString \
		IO/Octets.h \
		../Qt/5.10.0/Static/include/QtCore/QByteArray
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Utils.o Utils.cpp

BroadcasterWorker.o: Workers/BroadcasterWorker.cpp Workers/BroadcasterWorker.h \
		../Qt/5.10.0/Static/include/QtCore/QObject \
		../Qt/5.10.0/Static/include/QtCore/qobject.h \
		../Qt/5.10.0/Static/include/QtCore/qobjectdefs.h \
		../Qt/5.10.0/Static/include/QtCore/qnamespace.h \
		../Qt/5.10.0/Static/include/QtCore/qglobal.h \
		../Qt/5.10.0/Static/include/QtCore/qconfig-bootstrapped.h \
		../Qt/5.10.0/Static/include/QtCore/qconfig.h \
		../Qt/5.10.0/Static/include/QtCore/qtcore-config.h \
		../Qt/5.10.0/Static/include/QtCore/qsystemdetection.h \
		../Qt/5.10.0/Static/include/QtCore/qprocessordetection.h \
		../Qt/5.10.0/Static/include/QtCore/qcompilerdetection.h \
		../Qt/5.10.0/Static/include/QtCore/qtypeinfo.h \
		../Qt/5.10.0/Static/include/QtCore/qsysinfo.h \
		../Qt/5.10.0/Static/include/QtCore/qlogging.h \
		../Qt/5.10.0/Static/include/QtCore/qflags.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic.h \
		../Qt/5.10.0/Static/include/QtCore/qbasicatomic.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic_bootstrap.h \
		../Qt/5.10.0/Static/include/QtCore/qgenericatomic.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic_cxx11.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic_msvc.h \
		../Qt/5.10.0/Static/include/QtCore/qglobalstatic.h \
		../Qt/5.10.0/Static/include/QtCore/qmutex.h \
		../Qt/5.10.0/Static/include/QtCore/qnumeric.h \
		../Qt/5.10.0/Static/include/QtCore/qversiontagging.h \
		../Qt/5.10.0/Static/include/QtCore/qobjectdefs_impl.h \
		../Qt/5.10.0/Static/include/QtCore/qstring.h \
		../Qt/5.10.0/Static/include/QtCore/qchar.h \
		../Qt/5.10.0/Static/include/QtCore/qbytearray.h \
		../Qt/5.10.0/Static/include/QtCore/qrefcount.h \
		../Qt/5.10.0/Static/include/QtCore/qarraydata.h \
		../Qt/5.10.0/Static/include/QtCore/qstringliteral.h \
		../Qt/5.10.0/Static/include/QtCore/qstringalgorithms.h \
		../Qt/5.10.0/Static/include/QtCore/qstringview.h \
		../Qt/5.10.0/Static/include/QtCore/qstringbuilder.h \
		../Qt/5.10.0/Static/include/QtCore/qlist.h \
		../Qt/5.10.0/Static/include/QtCore/qalgorithms.h \
		../Qt/5.10.0/Static/include/QtCore/qiterator.h \
		../Qt/5.10.0/Static/include/QtCore/qhashfunctions.h \
		../Qt/5.10.0/Static/include/QtCore/qpair.h \
		../Qt/5.10.0/Static/include/QtCore/qbytearraylist.h \
		../Qt/5.10.0/Static/include/QtCore/qstringlist.h \
		../Qt/5.10.0/Static/include/QtCore/qregexp.h \
		../Qt/5.10.0/Static/include/QtCore/qstringmatcher.h \
		../Qt/5.10.0/Static/include/QtCore/qcoreevent.h \
		../Qt/5.10.0/Static/include/QtCore/qscopedpointer.h \
		../Qt/5.10.0/Static/include/QtCore/qmetatype.h \
		../Qt/5.10.0/Static/include/QtCore/qvarlengtharray.h \
		../Qt/5.10.0/Static/include/QtCore/qcontainerfwd.h \
		../Qt/5.10.0/Static/include/QtCore/qobject_impl.h \
		../Qt/5.10.0/Static/include/QtCore/QFile \
		../Qt/5.10.0/Static/include/QtCore/qfile.h \
		../Qt/5.10.0/Static/include/QtCore/qfiledevice.h \
		../Qt/5.10.0/Static/include/QtCore/qiodevice.h \
		../Qt/5.10.0/Static/include/QtCore/QTimer \
		../Qt/5.10.0/Static/include/QtCore/qtimer.h \
		../Qt/5.10.0/Static/include/QtCore/qbasictimer.h \
		Settings.h \
		../Qt/5.10.0/Static/include/QtCore/QVariant \
		../Qt/5.10.0/Static/include/QtCore/qvariant.h \
		../Qt/5.10.0/Static/include/QtCore/qmap.h \
		../Qt/5.10.0/Static/include/QtCore/qdebug.h \
		../Qt/5.10.0/Static/include/QtCore/qhash.h \
		../Qt/5.10.0/Static/include/QtCore/qtextstream.h \
		../Qt/5.10.0/Static/include/QtCore/qlocale.h \
		../Qt/5.10.0/Static/include/QtCore/qshareddata.h \
		../Qt/5.10.0/Static/include/QtCore/qvector.h \
		../Qt/5.10.0/Static/include/QtCore/qpoint.h \
		../Qt/5.10.0/Static/include/QtCore/qset.h \
		../Qt/5.10.0/Static/include/QtCore/qcontiguouscache.h \
		../Qt/5.10.0/Static/include/QtCore/qsharedpointer.h \
		../Qt/5.10.0/Static/include/QtCore/qsharedpointer_impl.h \
		../Qt/5.10.0/Static/include/QtCore/QSettings \
		../Qt/5.10.0/Static/include/QtCore/qsettings.h \
		../Qt/5.10.0/Static/include/QtCore/QMetaEnum \
		../Qt/5.10.0/Static/include/QtCore/qmetaobject.h \
		../Qt/5.10.0/Static/include/QtCore/QRegExp \
		../Qt/5.10.0/Static/include/QtCore/QList \
		Utils.h \
		../Qt/5.10.0/Static/include/QtCore/QTextCodec \
		../Qt/5.10.0/Static/include/QtCore/qtextcodec.h \
		../Qt/5.10.0/Static/include/QtCore/QDateTime \
		../Qt/5.10.0/Static/include/QtCore/qdatetime.h \
		../Qt/5.10.0/Static/include/QtCore/QString \
		IO/Octets.h \
		../Qt/5.10.0/Static/include/QtCore/QByteArray \
		Network/GDeliveryd.h \
		../Qt/5.10.0/Static/include/QtNetwork/QTcpSocket \
		../Qt/5.10.0/Static/include/QtNetwork/qtcpsocket.h \
		../Qt/5.10.0/Static/include/QtNetwork/qtnetworkglobal.h \
		../Qt/5.10.0/Static/include/QtNetwork/qtnetwork-config.h \
		../Qt/5.10.0/Static/include/QtNetwork/qabstractsocket.h \
		Protocols/WorldChat.h \
		IO/OctetsStream.h \
		../Qt/5.10.0/Static/include/QtCore/QDataStream \
		../Qt/5.10.0/Static/include/QtCore/qdatastream.h \
		../Qt/5.10.0/Static/include/QtCore/QtEndian \
		../Qt/5.10.0/Static/include/QtCore/qendian.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BroadcasterWorker.o Workers/BroadcasterWorker.cpp

echoserver.o: echoserver.cpp echoserver.h \
		../Qt/5.10.0/Static/include/QtCore/QObject \
		../Qt/5.10.0/Static/include/QtCore/qobject.h \
		../Qt/5.10.0/Static/include/QtCore/qobjectdefs.h \
		../Qt/5.10.0/Static/include/QtCore/qnamespace.h \
		../Qt/5.10.0/Static/include/QtCore/qglobal.h \
		../Qt/5.10.0/Static/include/QtCore/qconfig-bootstrapped.h \
		../Qt/5.10.0/Static/include/QtCore/qconfig.h \
		../Qt/5.10.0/Static/include/QtCore/qtcore-config.h \
		../Qt/5.10.0/Static/include/QtCore/qsystemdetection.h \
		../Qt/5.10.0/Static/include/QtCore/qprocessordetection.h \
		../Qt/5.10.0/Static/include/QtCore/qcompilerdetection.h \
		../Qt/5.10.0/Static/include/QtCore/qtypeinfo.h \
		../Qt/5.10.0/Static/include/QtCore/qsysinfo.h \
		../Qt/5.10.0/Static/include/QtCore/qlogging.h \
		../Qt/5.10.0/Static/include/QtCore/qflags.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic.h \
		../Qt/5.10.0/Static/include/QtCore/qbasicatomic.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic_bootstrap.h \
		../Qt/5.10.0/Static/include/QtCore/qgenericatomic.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic_cxx11.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic_msvc.h \
		../Qt/5.10.0/Static/include/QtCore/qglobalstatic.h \
		../Qt/5.10.0/Static/include/QtCore/qmutex.h \
		../Qt/5.10.0/Static/include/QtCore/qnumeric.h \
		../Qt/5.10.0/Static/include/QtCore/qversiontagging.h \
		../Qt/5.10.0/Static/include/QtCore/qobjectdefs_impl.h \
		../Qt/5.10.0/Static/include/QtCore/qstring.h \
		../Qt/5.10.0/Static/include/QtCore/qchar.h \
		../Qt/5.10.0/Static/include/QtCore/qbytearray.h \
		../Qt/5.10.0/Static/include/QtCore/qrefcount.h \
		../Qt/5.10.0/Static/include/QtCore/qarraydata.h \
		../Qt/5.10.0/Static/include/QtCore/qstringliteral.h \
		../Qt/5.10.0/Static/include/QtCore/qstringalgorithms.h \
		../Qt/5.10.0/Static/include/QtCore/qstringview.h \
		../Qt/5.10.0/Static/include/QtCore/qstringbuilder.h \
		../Qt/5.10.0/Static/include/QtCore/qlist.h \
		../Qt/5.10.0/Static/include/QtCore/qalgorithms.h \
		../Qt/5.10.0/Static/include/QtCore/qiterator.h \
		../Qt/5.10.0/Static/include/QtCore/qhashfunctions.h \
		../Qt/5.10.0/Static/include/QtCore/qpair.h \
		../Qt/5.10.0/Static/include/QtCore/qbytearraylist.h \
		../Qt/5.10.0/Static/include/QtCore/qstringlist.h \
		../Qt/5.10.0/Static/include/QtCore/qregexp.h \
		../Qt/5.10.0/Static/include/QtCore/qstringmatcher.h \
		../Qt/5.10.0/Static/include/QtCore/qcoreevent.h \
		../Qt/5.10.0/Static/include/QtCore/qscopedpointer.h \
		../Qt/5.10.0/Static/include/QtCore/qmetatype.h \
		../Qt/5.10.0/Static/include/QtCore/qvarlengtharray.h \
		../Qt/5.10.0/Static/include/QtCore/qcontainerfwd.h \
		../Qt/5.10.0/Static/include/QtCore/qobject_impl.h \
		../Qt/5.10.0/Static/include/QtCore/QList \
		../Qt/5.10.0/Static/include/QtCore/QByteArray \
		../Qt/5.10.0/Static/include/QtNetwork/QTcpSocket \
		../Qt/5.10.0/Static/include/QtNetwork/qtcpsocket.h \
		../Qt/5.10.0/Static/include/QtNetwork/qtnetworkglobal.h \
		../Qt/5.10.0/Static/include/QtNetwork/qtnetwork-config.h \
		../Qt/5.10.0/Static/include/QtNetwork/qabstractsocket.h \
		../Qt/5.10.0/Static/include/QtCore/qiodevice.h \
		../Qt/5.10.0/Static/include/QtCore/qdebug.h \
		../Qt/5.10.0/Static/include/QtCore/qhash.h \
		../Qt/5.10.0/Static/include/QtCore/qmap.h \
		../Qt/5.10.0/Static/include/QtCore/qtextstream.h \
		../Qt/5.10.0/Static/include/QtCore/qlocale.h \
		../Qt/5.10.0/Static/include/QtCore/qvariant.h \
		../Qt/5.10.0/Static/include/QtCore/qshareddata.h \
		../Qt/5.10.0/Static/include/QtCore/qvector.h \
		../Qt/5.10.0/Static/include/QtCore/qpoint.h \
		../Qt/5.10.0/Static/include/QtCore/qset.h \
		../Qt/5.10.0/Static/include/QtCore/qcontiguouscache.h \
		../Qt/5.10.0/Static/include/QtCore/qsharedpointer.h \
		../Qt/5.10.0/Static/include/QtCore/qsharedpointer_impl.h \
		../Qt/5.10.0/Static/include/QtWebSockets/qwebsocketserver.h \
		../Qt/5.10.0/Static/include/QtWebSockets/qwebsockets_global.h \
		../Qt/5.10.0/Static/include/QtWebSockets/qwebsocketprotocol.h \
		../Qt/5.10.0/Static/include/QtCore/QString \
		../Qt/5.10.0/Static/include/QtNetwork/QHostAddress \
		../Qt/5.10.0/Static/include/QtNetwork/qhostaddress.h \
		../Qt/5.10.0/Static/include/QtNetwork/QSslConfiguration \
		../Qt/5.10.0/Static/include/QtNetwork/qsslconfiguration.h \
		../Qt/5.10.0/Static/include/QtNetwork/qsslsocket.h \
		../Qt/5.10.0/Static/include/QtNetwork/qsslerror.h \
		../Qt/5.10.0/Static/include/QtNetwork/qsslcertificate.h \
		../Qt/5.10.0/Static/include/QtCore/qcryptographichash.h \
		../Qt/5.10.0/Static/include/QtCore/qdatetime.h \
		../Qt/5.10.0/Static/include/QtNetwork/qssl.h \
		../Qt/5.10.0/Static/include/QtCore/QFlags \
		../Qt/5.10.0/Static/include/QtNetwork/QSslError \
		../Qt/5.10.0/Static/include/QtWebSockets/qwebsocket.h \
		../Qt/5.10.0/Static/include/QtCore/QUrl \
		../Qt/5.10.0/Static/include/QtCore/qurl.h \
		../Qt/5.10.0/Static/include/QtCore/qurlquery.h \
		../Qt/5.10.0/Static/include/QtNetwork/QAbstractSocket \
		../Qt/5.10.0/Static/include/QtNetwork/QNetworkRequest \
		../Qt/5.10.0/Static/include/QtNetwork/qnetworkrequest.h \
		../Qt/5.10.0/Static/include/QtCore/QSharedDataPointer \
		../Qt/5.10.0/Static/include/QtCore/QVariant \
		../Qt/5.10.0/Static/include/QtNetwork/QNetworkProxy \
		../Qt/5.10.0/Static/include/QtNetwork/qnetworkproxy.h \
		../Qt/5.10.0/Static/include/QtCore/QDebug \
		IO/Octets.h \
		IO/OctetsStream.h \
		../Qt/5.10.0/Static/include/QtCore/QDataStream \
		../Qt/5.10.0/Static/include/QtCore/qdatastream.h \
		../Qt/5.10.0/Static/include/QtCore/QtEndian \
		../Qt/5.10.0/Static/include/QtCore/qendian.h \
		Utils.h \
		../Qt/5.10.0/Static/include/QtCore/QTextCodec \
		../Qt/5.10.0/Static/include/QtCore/qtextcodec.h \
		../Qt/5.10.0/Static/include/QtCore/QDateTime \
		Settings.h \
		../Qt/5.10.0/Static/include/QtCore/QSettings \
		../Qt/5.10.0/Static/include/QtCore/qsettings.h \
		../Qt/5.10.0/Static/include/QtCore/QMetaEnum \
		../Qt/5.10.0/Static/include/QtCore/qmetaobject.h \
		../Qt/5.10.0/Static/include/QtCore/QRegExp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o echoserver.o echoserver.cpp

Server.o: Server.cpp Server.h \
		../Qt/5.10.0/Static/include/QtCore/QObject \
		../Qt/5.10.0/Static/include/QtCore/qobject.h \
		../Qt/5.10.0/Static/include/QtCore/qobjectdefs.h \
		../Qt/5.10.0/Static/include/QtCore/qnamespace.h \
		../Qt/5.10.0/Static/include/QtCore/qglobal.h \
		../Qt/5.10.0/Static/include/QtCore/qconfig-bootstrapped.h \
		../Qt/5.10.0/Static/include/QtCore/qconfig.h \
		../Qt/5.10.0/Static/include/QtCore/qtcore-config.h \
		../Qt/5.10.0/Static/include/QtCore/qsystemdetection.h \
		../Qt/5.10.0/Static/include/QtCore/qprocessordetection.h \
		../Qt/5.10.0/Static/include/QtCore/qcompilerdetection.h \
		../Qt/5.10.0/Static/include/QtCore/qtypeinfo.h \
		../Qt/5.10.0/Static/include/QtCore/qsysinfo.h \
		../Qt/5.10.0/Static/include/QtCore/qlogging.h \
		../Qt/5.10.0/Static/include/QtCore/qflags.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic.h \
		../Qt/5.10.0/Static/include/QtCore/qbasicatomic.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic_bootstrap.h \
		../Qt/5.10.0/Static/include/QtCore/qgenericatomic.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic_cxx11.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic_msvc.h \
		../Qt/5.10.0/Static/include/QtCore/qglobalstatic.h \
		../Qt/5.10.0/Static/include/QtCore/qmutex.h \
		../Qt/5.10.0/Static/include/QtCore/qnumeric.h \
		../Qt/5.10.0/Static/include/QtCore/qversiontagging.h \
		../Qt/5.10.0/Static/include/QtCore/qobjectdefs_impl.h \
		../Qt/5.10.0/Static/include/QtCore/qstring.h \
		../Qt/5.10.0/Static/include/QtCore/qchar.h \
		../Qt/5.10.0/Static/include/QtCore/qbytearray.h \
		../Qt/5.10.0/Static/include/QtCore/qrefcount.h \
		../Qt/5.10.0/Static/include/QtCore/qarraydata.h \
		../Qt/5.10.0/Static/include/QtCore/qstringliteral.h \
		../Qt/5.10.0/Static/include/QtCore/qstringalgorithms.h \
		../Qt/5.10.0/Static/include/QtCore/qstringview.h \
		../Qt/5.10.0/Static/include/QtCore/qstringbuilder.h \
		../Qt/5.10.0/Static/include/QtCore/qlist.h \
		../Qt/5.10.0/Static/include/QtCore/qalgorithms.h \
		../Qt/5.10.0/Static/include/QtCore/qiterator.h \
		../Qt/5.10.0/Static/include/QtCore/qhashfunctions.h \
		../Qt/5.10.0/Static/include/QtCore/qpair.h \
		../Qt/5.10.0/Static/include/QtCore/qbytearraylist.h \
		../Qt/5.10.0/Static/include/QtCore/qstringlist.h \
		../Qt/5.10.0/Static/include/QtCore/qregexp.h \
		../Qt/5.10.0/Static/include/QtCore/qstringmatcher.h \
		../Qt/5.10.0/Static/include/QtCore/qcoreevent.h \
		../Qt/5.10.0/Static/include/QtCore/qscopedpointer.h \
		../Qt/5.10.0/Static/include/QtCore/qmetatype.h \
		../Qt/5.10.0/Static/include/QtCore/qvarlengtharray.h \
		../Qt/5.10.0/Static/include/QtCore/qcontainerfwd.h \
		../Qt/5.10.0/Static/include/QtCore/qobject_impl.h \
		../Qt/5.10.0/Static/include/QtNetwork/QTcpSocket \
		../Qt/5.10.0/Static/include/QtNetwork/qtcpsocket.h \
		../Qt/5.10.0/Static/include/QtNetwork/qtnetworkglobal.h \
		../Qt/5.10.0/Static/include/QtNetwork/qtnetwork-config.h \
		../Qt/5.10.0/Static/include/QtNetwork/qabstractsocket.h \
		../Qt/5.10.0/Static/include/QtCore/qiodevice.h \
		../Qt/5.10.0/Static/include/QtCore/qdebug.h \
		../Qt/5.10.0/Static/include/QtCore/qhash.h \
		../Qt/5.10.0/Static/include/QtCore/qmap.h \
		../Qt/5.10.0/Static/include/QtCore/qtextstream.h \
		../Qt/5.10.0/Static/include/QtCore/qlocale.h \
		../Qt/5.10.0/Static/include/QtCore/qvariant.h \
		../Qt/5.10.0/Static/include/QtCore/qshareddata.h \
		../Qt/5.10.0/Static/include/QtCore/qvector.h \
		../Qt/5.10.0/Static/include/QtCore/qpoint.h \
		../Qt/5.10.0/Static/include/QtCore/qset.h \
		../Qt/5.10.0/Static/include/QtCore/qcontiguouscache.h \
		../Qt/5.10.0/Static/include/QtCore/qsharedpointer.h \
		../Qt/5.10.0/Static/include/QtCore/qsharedpointer_impl.h \
		Settings.h \
		../Qt/5.10.0/Static/include/QtCore/QVariant \
		../Qt/5.10.0/Static/include/QtCore/QSettings \
		../Qt/5.10.0/Static/include/QtCore/qsettings.h \
		../Qt/5.10.0/Static/include/QtCore/QMetaEnum \
		../Qt/5.10.0/Static/include/QtCore/qmetaobject.h \
		../Qt/5.10.0/Static/include/QtCore/QRegExp \
		../Qt/5.10.0/Static/include/QtCore/QList \
		Utils.h \
		../Qt/5.10.0/Static/include/QtCore/QTextCodec \
		../Qt/5.10.0/Static/include/QtCore/qtextcodec.h \
		../Qt/5.10.0/Static/include/QtCore/QDateTime \
		../Qt/5.10.0/Static/include/QtCore/qdatetime.h \
		../Qt/5.10.0/Static/include/QtCore/QString \
		IO/Octets.h \
		../Qt/5.10.0/Static/include/QtCore/QByteArray \
		../Qt/5.10.0/Static/include/QtNetwork/QHostAddress \
		../Qt/5.10.0/Static/include/QtNetwork/qhostaddress.h \
		../Qt/5.10.0/Static/include/QtCore/QJsonDocument \
		../Qt/5.10.0/Static/include/QtCore/qjsondocument.h \
		../Qt/5.10.0/Static/include/QtCore/qjsonvalue.h \
		../Qt/5.10.0/Static/include/QtCore/QJsonObject \
		../Qt/5.10.0/Static/include/QtCore/qjsonobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Server.o Server.cpp

main.o: main.cpp ../Qt/5.10.0/Static/include/QtCore/QCoreApplication \
		../Qt/5.10.0/Static/include/QtCore/qcoreapplication.h \
		../Qt/5.10.0/Static/include/QtCore/qglobal.h \
		../Qt/5.10.0/Static/include/QtCore/qconfig-bootstrapped.h \
		../Qt/5.10.0/Static/include/QtCore/qconfig.h \
		../Qt/5.10.0/Static/include/QtCore/qtcore-config.h \
		../Qt/5.10.0/Static/include/QtCore/qsystemdetection.h \
		../Qt/5.10.0/Static/include/QtCore/qprocessordetection.h \
		../Qt/5.10.0/Static/include/QtCore/qcompilerdetection.h \
		../Qt/5.10.0/Static/include/QtCore/qtypeinfo.h \
		../Qt/5.10.0/Static/include/QtCore/qsysinfo.h \
		../Qt/5.10.0/Static/include/QtCore/qlogging.h \
		../Qt/5.10.0/Static/include/QtCore/qflags.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic.h \
		../Qt/5.10.0/Static/include/QtCore/qbasicatomic.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic_bootstrap.h \
		../Qt/5.10.0/Static/include/QtCore/qgenericatomic.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic_cxx11.h \
		../Qt/5.10.0/Static/include/QtCore/qatomic_msvc.h \
		../Qt/5.10.0/Static/include/QtCore/qglobalstatic.h \
		../Qt/5.10.0/Static/include/QtCore/qmutex.h \
		../Qt/5.10.0/Static/include/QtCore/qnumeric.h \
		../Qt/5.10.0/Static/include/QtCore/qversiontagging.h \
		../Qt/5.10.0/Static/include/QtCore/qstring.h \
		../Qt/5.10.0/Static/include/QtCore/qchar.h \
		../Qt/5.10.0/Static/include/QtCore/qbytearray.h \
		../Qt/5.10.0/Static/include/QtCore/qrefcount.h \
		../Qt/5.10.0/Static/include/QtCore/qnamespace.h \
		../Qt/5.10.0/Static/include/QtCore/qarraydata.h \
		../Qt/5.10.0/Static/include/QtCore/qstringliteral.h \
		../Qt/5.10.0/Static/include/QtCore/qstringalgorithms.h \
		../Qt/5.10.0/Static/include/QtCore/qstringview.h \
		../Qt/5.10.0/Static/include/QtCore/qstringbuilder.h \
		../Qt/5.10.0/Static/include/QtCore/qobject.h \
		../Qt/5.10.0/Static/include/QtCore/qobjectdefs.h \
		../Qt/5.10.0/Static/include/QtCore/qobjectdefs_impl.h \
		../Qt/5.10.0/Static/include/QtCore/qlist.h \
		../Qt/5.10.0/Static/include/QtCore/qalgorithms.h \
		../Qt/5.10.0/Static/include/QtCore/qiterator.h \
		../Qt/5.10.0/Static/include/QtCore/qhashfunctions.h \
		../Qt/5.10.0/Static/include/QtCore/qpair.h \
		../Qt/5.10.0/Static/include/QtCore/qbytearraylist.h \
		../Qt/5.10.0/Static/include/QtCore/qstringlist.h \
		../Qt/5.10.0/Static/include/QtCore/qregexp.h \
		../Qt/5.10.0/Static/include/QtCore/qstringmatcher.h \
		../Qt/5.10.0/Static/include/QtCore/qcoreevent.h \
		../Qt/5.10.0/Static/include/QtCore/qscopedpointer.h \
		../Qt/5.10.0/Static/include/QtCore/qmetatype.h \
		../Qt/5.10.0/Static/include/QtCore/qvarlengtharray.h \
		../Qt/5.10.0/Static/include/QtCore/qcontainerfwd.h \
		../Qt/5.10.0/Static/include/QtCore/qobject_impl.h \
		../Qt/5.10.0/Static/include/QtCore/qeventloop.h \
		echoserver.h \
		../Qt/5.10.0/Static/include/QtCore/QObject \
		../Qt/5.10.0/Static/include/QtCore/QList \
		../Qt/5.10.0/Static/include/QtCore/QByteArray \
		../Qt/5.10.0/Static/include/QtNetwork/QTcpSocket \
		../Qt/5.10.0/Static/include/QtNetwork/qtcpsocket.h \
		../Qt/5.10.0/Static/include/QtNetwork/qtnetworkglobal.h \
		../Qt/5.10.0/Static/include/QtNetwork/qtnetwork-config.h \
		../Qt/5.10.0/Static/include/QtNetwork/qabstractsocket.h \
		../Qt/5.10.0/Static/include/QtCore/qiodevice.h \
		../Qt/5.10.0/Static/include/QtCore/qdebug.h \
		../Qt/5.10.0/Static/include/QtCore/qhash.h \
		../Qt/5.10.0/Static/include/QtCore/qmap.h \
		../Qt/5.10.0/Static/include/QtCore/qtextstream.h \
		../Qt/5.10.0/Static/include/QtCore/qlocale.h \
		../Qt/5.10.0/Static/include/QtCore/qvariant.h \
		../Qt/5.10.0/Static/include/QtCore/qshareddata.h \
		../Qt/5.10.0/Static/include/QtCore/qvector.h \
		../Qt/5.10.0/Static/include/QtCore/qpoint.h \
		../Qt/5.10.0/Static/include/QtCore/qset.h \
		../Qt/5.10.0/Static/include/QtCore/qcontiguouscache.h \
		../Qt/5.10.0/Static/include/QtCore/qsharedpointer.h \
		../Qt/5.10.0/Static/include/QtCore/qsharedpointer_impl.h \
		Utils.h \
		../Qt/5.10.0/Static/include/QtCore/QTextCodec \
		../Qt/5.10.0/Static/include/QtCore/qtextcodec.h \
		../Qt/5.10.0/Static/include/QtCore/QDateTime \
		../Qt/5.10.0/Static/include/QtCore/qdatetime.h \
		../Qt/5.10.0/Static/include/QtCore/QString \
		IO/Octets.h \
		Settings.h \
		../Qt/5.10.0/Static/include/QtCore/QVariant \
		../Qt/5.10.0/Static/include/QtCore/QSettings \
		../Qt/5.10.0/Static/include/QtCore/qsettings.h \
		../Qt/5.10.0/Static/include/QtCore/QMetaEnum \
		../Qt/5.10.0/Static/include/QtCore/qmetaobject.h \
		../Qt/5.10.0/Static/include/QtCore/QRegExp \
		Server.h \
		Network/GDeliveryd.h \
		Protocols/WorldChat.h \
		IO/OctetsStream.h \
		../Qt/5.10.0/Static/include/QtCore/QDataStream \
		../Qt/5.10.0/Static/include/QtCore/qdatastream.h \
		../Qt/5.10.0/Static/include/QtCore/QtEndian \
		../Qt/5.10.0/Static/include/QtCore/qendian.h \
		Workers/BroadcasterWorker.h \
		../Qt/5.10.0/Static/include/QtCore/QFile \
		../Qt/5.10.0/Static/include/QtCore/qfile.h \
		../Qt/5.10.0/Static/include/QtCore/qfiledevice.h \
		../Qt/5.10.0/Static/include/QtCore/QTimer \
		../Qt/5.10.0/Static/include/QtCore/qtimer.h \
		../Qt/5.10.0/Static/include/QtCore/qbasictimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

pwchat_plugin_import.o: /opt/pwhook0.2.0/pwchat_plugin_import.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pwchat_plugin_import.o /opt/pwhook0.2.0/pwchat_plugin_import.cpp

moc_GDeliveryd.o: moc_GDeliveryd.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GDeliveryd.o moc_GDeliveryd.cpp

moc_Server.o: moc_Server.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Server.o moc_Server.cpp

moc_BroadcasterWorker.o: moc_BroadcasterWorker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_BroadcasterWorker.o moc_BroadcasterWorker.cpp

moc_echoserver.o: moc_echoserver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_echoserver.o moc_echoserver.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

